name: PullRequestTest
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened] # Optional: specify types of PR events

  workflow_dispatch: # Allow manual triggering of the workflow
    inputs:
      target-branch:
        description: 'Target branch for the PR test'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Test svelte build
        run: npm run build

      - name: Test missing image srcs
        run: python3 ./src/lib/img/1testMissingImg.py
